--- # Tasks - PostgreSQL
- name: Installing PostgreSQL from APT
  apt:
    name: postgresql
    state: present
  notify:
    - start postgresql.service

- name: Creating 'odoo' PostgreSQL user
  become_user: postgres
  command: createuser -s odoo
