--- # Tasks - Odoo
  - name: Installing Odoo Dependencies from APT
    apt:
      name: "{{ item }}"
      state: present
    loop:
      - git
      - python3-pip 
      - build-essential 
      - wget 
      - python3-dev 
      - python3-venv 
      - python3-wheel 
      - libxslt-dev 
      - libzip-dev 
      - libldap2-dev 
      - libsasl2-dev 
      - python3-setuptools
      - net-tools
    ignore_errors: yes

  - name: Creating '/opt/odoo' Directory
    file:
      path: /opt/odoo
      state: directory
      owner: odoo

  - name: Creating 'wkhtmltopdf' Folder
    file:
      path: /opt/odoo/wkhtmltopdf
      state: directory
      owner: odoo

  - name: Downloading Wkhtmltopdf
    get_url:
        url: https://builds.wkhtmltopdf.org/0.12.1.3/wkhtmltox_0.12.1.3-1~bionic_amd64.deb
        dest: /opt/odoo/wkhtmltopdf/
        
  - name: Installing Wkhtmltopdf
    apt:
      deb: /opt/odoo/wkhtmltopdf/wkhtmltox_0.12.1.3-1~bionic_amd64.deb

  - name: Cloning Odoo Git Repo
    git:
      repo: 'https://github.com/odoo/odoo.git'
      dest: /opt/odoo/odoo11/
      version: '11.0'
      depth: 1

  - name: Installing Python Dependencies from PIP3
    pip:
      name: "{{ item }}"
      executable: pip3
    loop:
      - Babel==2.3.4
      - decorator==4.0.10
      - docutils==0.12
      - ebaysdk==2.1.5
      - feedparser==5.2.1
      - gevent==1.1.2
      - gevent==1.3.4
      - greenlet==0.4.10
      - greenlet==0.4.13
      - html2text==2016.9.19
      - Jinja2==2.10.1
      - lxml==3.7.1
      - lxml==4.2.3
      - lxml
      - Mako==1.0.4
      - MarkupSafe==0.23
      - mock==2.0.0
      - num2words==0.5.6
      - ofxparse==0.16
      - passlib==1.6.5
      - Pillow==4.0.0
      - psutil==4.3.1
      - psycopg2==2.7.3.1
      - pydot==1.2.3
      - pyldap==2.4.28
      - pyparsing==2.1.10
      - PyPDF2==1.26.0
      - pyserial==3.1.1
      - python-dateutil==2.5.3
      - pytz==2016.7
      - pyusb==1.0.0
      - PyYAML==3.12
      - PyYAML==3.13
      - qrcode==5.3
      - reportlab==3.3.0
      - requests==2.20.0
      - suds-jurko==0.6
      - vatnumber==1.2
      - vobject==0.9.3
      - Werkzeug==0.11.15
      - XlsxWriter==0.9.3
      - xlwt==1.3.*
      - xlrd==1.0.0
    ignore_errors: yes
    
  - name: Copying odoo-server.service
    copy:
      src: files/odoo-server.service
      dest: /lib/systemd/system/odoo-server.service
      owner: odoo
  
  - name: Cloning New-Relic Git Repo
    git:
      repo: 'https://github.com/hibou-io/odoo-newrelic'
      dest: /opt/odoo/new-relic/
      version: '10.0'
      depth: 1
  
  - name: Copying New-Relic to Addons Folder
    copy:
      src: /opt/odoo/new-relic/newrelic
      dest: /opt/odoo/odoo11/addons/
  
  - name: Creating /var/log/odoo Folder
    file:
      path: /var/log/odoo
      state: directory
      owner: odoo
  
  - name: Copying Odoo Conf File
    copy:
      src: files/odoo-server.conf
      dest: /etc/odoo-server.conf
      owner: odoo
    notify:
    - start odoo-server.service
